#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generator script for Menorca GR-223 Camí de Cavalls scout hiking routes dataset.
Generates:
- data/rutes_menorca.json (22 routes: 20 official GR-223 stages + 2 key variants)

Strictly preserves data/rutes_mallorca.json 100% untouched.
Outputs strictly valid UTF-8 JSON without BOM.
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_FILE = DATA_DIR / "rutes_menorca.json"

STAGES_DATA = [
    (
        "gr223-etapa-01-mao-es-grau",
        "GR-223 Etapa 1: Maó a Es Grau",
        "Maó",
        "Llevant de Menorca",
        10.0,
        110,
        "Moderada",
        "3h 15min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Port de Maó (inici)", "Sa Mesquida", "Es Grau (final)"],
        "Tram inicial d'asfalt compartit a la sortida del port de Maó; extremar la vigilància del trànsit rodat. Zona molt assolellada sense ombra a Binillautí; dur calçat ferm, gorra i protecció solar.",
        "Primera etapa del Camí de Cavalls que surt del port de Maó, passa per la cala de Sa Mesquida amb la seva torre de defensa i s'endinsa al Parc Natural de s'Albufera des Grau.",
        39.8942,
        4.2647,
        "Culàrsega del Port de Maó",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+1+Mao+Es+Grau",
        ["Port de Maó", "Torre de Sa Mesquida", "Cala Binillautí", "Parc Natural de s'Albufera des Grau"],
        [[39.8942, 4.2647], [39.9120, 4.2860], [39.9350, 4.2750], [39.9515, 4.2682]],
    ),
    (
        "gr223-etapa-02-es-grau-favaritx",
        "GR-223 Etapa 2: Es Grau a Cap de Favàritx",
        "Maó",
        "Parc Natural de s'Albufera des Grau",
        8.6,
        135,
        "Moderada",
        "3h 00min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Es Grau (inici)", "Nul a Favàritx (dur reserva completa)"],
        "Pissarres negres que absorbeixen molta calor a l'estiu; terreny completament desabrigat sense ombra. Mínim 2.5L d'aigua per escolta. Respectar els camins senyalitzats per no malmetre la flora dunar.",
        "Travessa el cor del Parc Natural de s'Albufera des Grau vorejant cales verges com Cala Tortuga i Cala Presili fins a l'espectacular paisatge geològic lunar del Cap de Favàritx.",
        39.9515,
        4.2682,
        "Platja des Grau (accés Parc Natural)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+2+Es+Grau+Favaritx",
        ["Platja des Grau", "Cala de Sa Torreta", "Cala Tortuga", "Cala Presili", "Far de Favàritx"],
        [[39.9515, 4.2682], [39.9650, 4.2600], [39.9780, 4.2580], [39.9880, 4.2520]],
    ),
    (
        "gr223-etapa-03-favaritx-arenal-castell",
        "GR-223 Etapa 3: Favàritx a Arenal d'en Castell",
        "Es Mercadal",
        "Nord de Menorca",
        13.6,
        230,
        "Moderada",
        "4h 15min",
        ["Pioners/Rangers", "Rutes"],
        ["Arenal d'en Castell (final)", "Cap punt intermedi"],
        "Tram llarg, aïllat i molt pedregós ('trencapies'). Expost a forts cops de vent de tramuntana. Portar reserva d'aigua suficient (mínim 2.5L per persona) i farmaciola per rascades i torçades.",
        "Recorregut costaner agreste que voreja les salines de Mongofre, el Port d'Addaia i cales verges com Cala Pudenta, acabant a la badia semicircular d'Arenal d'en Castell.",
        39.9880,
        4.2520,
        "Carretera d'accés al Far de Favàritx",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+3+Favaritx+Arenal+Castell",
        ["Far de Favàritx", "Salines de Mongofre", "Pou d'en Caldes", "Port d'Addaia", "Arenal d'en Castell"],
        [[39.9880, 4.2520], [39.9980, 4.2250], [40.0050, 4.1980], [40.0215, 4.1835]],
    ),
    (
        "gr223-etapa-04-arenal-castell-cala-tirant",
        "GR-223 Etapa 4: Arenal d'en Castell a Cala Tirant",
        "Es Mercadal",
        "Nord de Menorca",
        10.8,
        160,
        "Fàcil",
        "3h 00min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Arenal d'en Castell (inici)", "Son Parc", "Cala Tirant (final)"],
        "Precaució als creuaments vials a Son Parc. Etapa assequible i planera apte per a branques joves. Calçat adequat per a trams de sorra a Son Saura del Nord i pista forestal.",
        "Etapa costanera assequible que connecta Arenal d'en Castell amb Son Saura del Nord, la platja de Son Parc i la gran badia verge de Cala Tirant.",
        40.0215,
        4.1835,
        "Arenal d'en Castell (passeig marítim)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+4+Arenal+Castell+Cala+Tirant",
        ["Arenal d'en Castell", "Son Saura del Nord", "Platja de Son Parc", "Cala Tirant"],
        [[40.0215, 4.1835], [40.0310, 4.1620], [40.0320, 4.1500], [40.0450, 4.1130]],
    ),
    (
        "gr223-etapa-05-cala-tirant-binimella",
        "GR-223 Etapa 5: Cala Tirant a Binimel·là",
        "Es Mercadal",
        "Nord de Menorca",
        9.6,
        175,
        "Moderada",
        "3h 00min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Cala Tirant (inici)", "Binimel·là (estiu, restaurant)"],
        "Respectar i protegir el fràgil sistema dunar de Cavalleria transitant estrictament per les passarel·les. Sol intens i terreny argilós vermellós amb còdols solts. Portar mínim 2.5 litres d'aigua per persona ja que no hi ha punts d'aigua potable garantits en tot el tram.",
        "Trajecte espectacular pel nord menorquí vorejant la platja de Cavalleria, el port natural de Sanitja i culminant a la platja salvatge de Binimel·là.",
        40.0450,
        4.1130,
        "Aparcament de Cala Tirant",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+5+Cala+Tirant+Binimella",
        ["Cala Tirant", "Port de Sanitja", "Platja de Cavalleria", "Platja de Binimel·là"],
        [[40.0450, 4.1130], [40.0510, 4.0950], [40.0580, 4.0750], [40.0520, 4.0530]],
    ),
    (
        "gr223-etapa-06-binimella-els-alocs",
        "GR-223 Etapa 6: Binimel·là a Els Alocs",
        "Ferreries",
        "Nord de Menorca",
        8.9,
        280,
        "Exigent",
        "3h 45min",
        ["Pioners/Rangers", "Rutes"],
        ["Nul en tot el tram (100% verge)"],
        "Etapa més exigent de l'illa sense cap punt d'aigua en tot el tram (100% verge). Risc elevat de cop de calor; obligatori dur mínim 3 litres d'aigua per persona. Fort pendís a Calderer; només apte per a Pioners i Rutes.",
        "L'etapa més salvatge i muntanyosa del Camí de Cavalls, passant per Cala Pregonda, Cala Barril i Cala en Calderer entre penya-segats abruptes i valls verges.",
        40.0520,
        4.0530,
        "Platja de Binimel·là",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+6+Binimella+Els+Alocs",
        ["Cala Pregonda", "Illot de Pregonda", "Cala Barril", "Cala en Calderer", "Els Alocs"],
        [[40.0520, 4.0530], [40.0560, 4.0410], [40.0590, 4.0200], [40.0600, 3.9990], [40.0570, 3.9850]],
    ),
    (
        "gr223-etapa-07-els-alocs-algaiarens",
        "GR-223 Etapa 7: Els Alocs a Algaiarens (La Vall)",
        "Ciutadella",
        "Nord de Menorca",
        9.7,
        345,
        "Exigent",
        "4h 00min",
        ["Pioners/Rangers", "Rutes"],
        ["Nul en tot el tram (font de Cala Pilar no tractada)"],
        "Terreny molt agreste amb grava solta al Coll de Cala Pilar. Cobertura de telefonia mòbil molt baixa o nul·la. Mínim 3 litres d'aigua per persona. Només apte per a unitats majors.",
        "Travessa el paisatge vermellós de Cala Pilar i el Pla de Mar fins a les frondoses pinedes i platges verges de sorra blanca de la Vall d'Algaiarens.",
        40.0570,
        3.9850,
        "Cala dels Alocs",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+7+Els+Alocs+Algaiarens",
        ["Cala dels Alocs", "Cala Pilar", "Coll del Pilar", "Pla de Mar", "Platja d'Algaiarens"],
        [[40.0570, 3.9850], [40.0550, 3.9720], [40.0520, 3.9480], [40.0460, 3.9210]],
    ),
    (
        "gr223-etapa-08-algaiarens-cala-morell",
        "GR-223 Etapa 8: Algaiarens a Cala Morell",
        "Ciutadella",
        "Ponent de Menorca",
        5.4,
        150,
        "Fàcil",
        "1h 45min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Cala Morell (nucli urbà final)"],
        "Pineda inicial amb bona ombra. Precaució a la zona de penya-segats i coves de la necròpolis talaiòtica de Cala Morell: no enfilar-se a les roques inestables.",
        "Etapa curta i agradable entre boscos de pi blanc que culmina a la cala protegida de Cala Morell amb la seva cèlebre necròpolis rupestre de coves talaiòtiques.",
        40.0460,
        3.9210,
        "Aparcament d'Algaiarens (La Vall)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+8+Algaiarens+Cala+Morell",
        ["Pineda de La Vall", "Ses Fontanelles", "Cala Morell", "Necròpolis talaiòtica de Cala Morell"],
        [[40.0460, 3.9210], [40.0480, 3.9100], [40.0510, 3.8950], [40.0540, 3.8820]],
    ),
    (
        "gr223-etapa-09-cala-morell-punta-nati",
        "GR-223 Etapa 9: Cala Morell a Punta Nati",
        "Ciutadella",
        "Ponent de Menorca",
        7.0,
        90,
        "Moderada",
        "2h 30min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Cala Morell (inici)", "Nul a Punta Nati"],
        "Terreny càrstic de pedra calcària esmolada sense cap ombra ('Menorca Seca'). Calçat de muntanya amb sola gruixuda obligatori i protecció solar alta per l'elevada reverberació.",
        "Paisatge imponent dominat per la pedra seca, barraques de bestiar tradicionals de gran volum i penya-segats marins fins al solitari Far de Punta Nati.",
        40.0540,
        3.8820,
        "Cala Morell (carrer de la Mar)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+9+Cala+Morell+Punta+Nati",
        ["Cala Morell", "Ses Roques Vermelles", "Barraques de pedra seca", "Far de Punta Nati"],
        [[40.0540, 3.8820], [40.0570, 3.8550], [40.0530, 3.8380], [40.0500, 3.8235]],
    ),
    (
        "gr223-etapa-10-punta-nati-ciutadella",
        "GR-223 Etapa 10: Punta Nati a Ciutadella",
        "Ciutadella",
        "Ponent de Menorca",
        10.5,
        100,
        "Fàcil",
        "3h 00min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Cala en Blanes", "Ciutadella de Menorca (nucli urbà)"],
        "Pas espectacular pel Pont d'en Gil sobre penya-segats verticals marins: aturar la marxa escolta en fila índia i evitar acostar-se a la vora en dies de vent fort. Tram final urbà.",
        "Des del far de Punta Nati resseguint la costa oest fins a l'arc natural del Pont d'en Gil, entrant a Ciutadella pel passeig marítim i el seu històric port antic.",
        40.0500,
        3.8235,
        "Far de Punta Nati",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+10+Punta+Nati+Ciutadella",
        ["Far de Punta Nati", "Pont d'en Gil", "Cala en Blanes", "Port històric de Ciutadella"],
        [[40.0500, 3.8235], [40.0120, 3.7960], [40.0080, 3.8150], [40.0010, 3.8370]],
    ),
    (
        "gr223-etapa-11-ciutadella-cap-dartrutx",
        "GR-223 Etapa 11: Ciutadella a Cap d'Artrutx",
        "Ciutadella",
        "Ponent de Menorca",
        13.2,
        45,
        "Fàcil",
        "3h 30min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Ciutadella (inici)", "Cala Blanca", "Cap d'Artrutx (final)"],
        "Camí pla de costa semiurbà. Assegurar protecció solar i aigua abundant durant els mesos càlids. Apte per a totes les branques escoltes gràcies al desnivell pràcticament nul.",
        "Sortida de Ciutadella resseguint la costa sud-oest passant per Cala Santandria, Cala Blanca i arribant al far emblemàtic de Cap d'Artrutx enfront de Mallorca.",
        40.0010,
        3.8370,
        "Plaça des Born (Ciutadella)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+11+Ciutadella+Cap+d+Artrutx",
        ["Plaça des Born", "Cala Santandria", "Cala Blanca", "Far de Cap d'Artrutx"],
        [[40.0010, 3.8370], [39.9780, 3.8350], [39.9650, 3.8330], [39.9230, 3.8240]],
    ),
    (
        "gr223-etapa-12-cap-dartrutx-cala-turqueta",
        "GR-223 Etapa 12: Cap d'Artrutx a Cala en Turqueta",
        "Ciutadella",
        "Sud de Menorca",
        13.3,
        85,
        "Moderada",
        "3h 45min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Cap d'Artrutx (inici)", "Aparcament Cala en Turqueta (estiu)"],
        "Roquissar pla molt obert i sense ombra als trams de Son Saura i Es Talaier. Calor persistent a l'estiu; dur mínim 2.5L d'aigua per persona i protecció solar completa.",
        "Etapa meridional que voreja les platges emblemàtiques de sorra blanca de Son Saura, Es Talaier i culmina a les famoses aigües turqueses de Cala en Turqueta.",
        39.9230,
        3.8240,
        "Far de Cap d'Artrutx",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+12+Cap+Artrutx+Cala+Turqueta",
        ["Far de Cap d'Artrutx", "Cala en Bosc", "Platges de Son Saura", "Es Talaier", "Cala en Turqueta"],
        [[39.9230, 3.8240], [39.9220, 3.8520], [39.9250, 3.8750], [39.9320, 3.9150]],
    ),
    (
        "gr223-etapa-13-cala-turqueta-cala-galdana",
        "GR-223 Etapa 13: Cala en Turqueta a Cala Galdana",
        "Ferreries",
        "Sud de Menorca",
        6.4,
        150,
        "Fàcil",
        "2h 00min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Macarella (estiu, serveis)", "Cala Galdana (final)"],
        "Pinedes d'ombra i esglaons de fusta. Respectar el sistema dunar protegit de Macarelleta. Prohibit fer foc; alt risc forestal d'incendi a l'estiu.",
        "Un dels trams més emblemàtics de Menorca que connecta Cala en Turqueta, Cala Macarella, Macarelleta i la badia protegida de Cala Galdana.",
        39.9320,
        3.9150,
        "Cala en Turqueta (àrea de serveis)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+13+Cala+Turqueta+Cala+Galdana",
        ["Cala en Turqueta", "Cala Macarelleta", "Cala Macarella", "Miradors de Cala Galdana"],
        [[39.9320, 3.9150], [39.9360, 3.9350], [39.9380, 3.9420], [39.9370, 3.9630]],
    ),
    (
        "gr223-etapa-14-cala-galdana-santo-tomas",
        "GR-223 Etapa 14: Cala Galdana a Santo Tomàs",
        "Es Migjorn Gran",
        "Sud de Menorca",
        10.8,
        240,
        "Moderada",
        "3h 30min",
        ["Pioners/Rangers", "Rutes"],
        ["Cala Galdana (inici)", "Santo Tomàs (final)"],
        "Travessa els barrancs abruptes de Trebalúger, Fustam i Escorxada. Terreny amb forts desnivells curts i fang relliscós en cas de pluja. Aïllament intermedi sense serveis.",
        "Recorregut per cales verges solitàries del sud menorquí com Cala Mitjana, Trebalúger, Cala Fustam i Cala Escorxada fins a arribar a Santo Tomàs.",
        39.9370,
        3.9630,
        "Cala Galdana (pont del riu Algendar)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+14+Cala+Galdana+Santo+Tomas",
        ["Cala Galdana", "Cala Mitjana", "Barranc de Trebalúger", "Cala Fustam", "Cala Escorxada", "Santo Tomàs"],
        [[39.9370, 3.9630], [39.9340, 3.9720], [39.9280, 3.9900], [39.9240, 4.0150], [39.9170, 4.0400]],
    ),
    (
        "gr223-etapa-15-santo-tomas-son-bou",
        "GR-223 Etapa 15: Santo Tomàs a Son Bou",
        "Alaior",
        "Sud de Menorca",
        6.4,
        70,
        "Fàcil",
        "1h 45min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Santo Tomàs (inici)", "Son Bou (final, botigues i fonts)"],
        "Platja de Son Bou i maresma protegida (Prat de Son Bou). Etapa molt plana i ràpida. Respectar la zona arqueològica de la basílica paleocristiana de Son Bou.",
        "Agradable passeig costaner que voreja la platja verge d'Atalis i la gran platja i maresma de Son Bou amb la seva basílica paleocristiana del segle V.",
        39.9170,
        4.0400,
        "Platja de Santo Tomàs",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+15+Santo+Tomas+Son+Bou",
        ["Platja de Santo Tomàs", "Platja d'Atalis", "Prat de Son Bou", "Basílica paleocristiana de Son Bou"],
        [[39.9170, 4.0400], [39.9120, 4.0530], [39.9050, 4.0620], [39.8990, 4.0720]],
    ),
    (
        "gr223-etapa-16-son-bou-cala-en-porter",
        "GR-223 Etapa 16: Son Bou a Cala en Porter",
        "Alaior",
        "Sud de Menorca",
        8.0,
        140,
        "Moderada",
        "2h 30min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Son Bou (inici)", "Cala en Porter (final)"],
        "Pas pels barrancs de Llucalari i Cala en Porter. Descensos amb còdols solts on cal vigilar les torçades de turmell. Forta xafogor a l'interior dels barrancs a l'estiu.",
        "Connexió entre Son Bou i Cala en Porter passant per la cala de còdols de Llucalari i l'interior rural de camps de conreu i parets de pedra seca tradicionals.",
        39.8990,
        4.0720,
        "Son Bou (estany des Prat)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+16+Son+Bou+Cala+en+Porter",
        ["Son Bou", "Cala Llucalari", "Barranc de Llucalari", "Barranc de Cala en Porter", "Cala en Porter"],
        [[39.8990, 4.0720], [39.8890, 4.0910], [39.8800, 4.1100], [39.8710, 4.1330]],
    ),
    (
        "gr223-etapa-17-cala-en-porter-binisafuller",
        "GR-223 Etapa 17: Cala en Porter a Binisafúller",
        "Sant Lluís",
        "Sud de Menorca",
        11.8,
        130,
        "Moderada",
        "3h 30min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Cala en Porter", "Es Canutells", "Binisafúller"],
        "Mosaic rural menorquí amb túnels de vegetació. Tancar sempre les barreres de bestiar de llenyam per respectar les finques ramaderes i evitar fugides d'animals.",
        "Recorregut pel sud-est menorquí visitant les cales de Calescoves (necròpolis talaiòtica), Es Canutells, Binisafúller i zones de camp tradicional.",
        39.8710,
        4.1330,
        "Platja de Cala en Porter",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+17+Cala+Porter+Binisafuller",
        ["Cala en Porter", "Calescoves (necròpolis)", "Es Canutells", "Binisafúller"],
        [[39.8710, 4.1330], [39.8650, 4.1480], [39.8520, 4.1700], [39.8290, 4.2050]],
    ),
    (
        "gr223-etapa-18-binisafuller-punta-prima",
        "GR-223 Etapa 18: Binisafúller a Punta Prima",
        "Sant Lluís",
        "Sud-Est de Menorca",
        8.1,
        55,
        "Fàcil",
        "2h 15min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Binisafúller", "Binibèquer Vell", "Punta Prima"],
        "Vials asfaltats i passeig marítim; compte amb el trànsit de vehicles a l'estiu. Vistes directes al far de l'Illa de l'Aire. Apte per a totes les unitats.",
        "Etapa planera que creua el poblat de pescadors de Binibèquer Vell, Biniancolla i arriba a la platja de Punta Prima enfront de la reserva de l'Illa de l'Aire.",
        39.8290,
        4.2050,
        "Caló Blanc / Binisafúller",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+18+Binisafuller+Punta+Prima",
        ["Caló Blanc", "Binibèquer Vell", "Biniancolla", "Platja de Punta Prima", "Far de l'Illa de l'Aire"],
        [[39.8290, 4.2050], [39.8220, 4.2250], [39.8180, 4.2550], [39.8140, 4.2810]],
    ),
    (
        "gr223-etapa-19-punta-prima-cala-sant-esteve",
        "GR-223 Etapa 19: Punta Prima a Cala de Sant Esteve",
        "Es Castell",
        "Llevant de Menorca",
        7.3,
        65,
        "Fàcil",
        "2h 00min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Punta Prima", "Alcalfar", "Cala de Sant Esteve"],
        "Bosc al Barranc de Rafalet d'alt valor ecològic; evitar sortir del sender marcat. Fort Marlborough i Torre d'Alcalfar al tram final amb penya-segats costaners.",
        "Trajecte oriental passant per la cala d'Alcalfar, el frondós barranc d'ombres de Rafalet i la fortificació històrica britànica de Fort Marlborough a Sant Esteve.",
        39.8140,
        4.2810,
        "Torre de Son Ganxo (Punta Prima)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+19+Punta+Prima+Cala+Sant+Esteve",
        ["Torre de Son Ganxo", "Cala d'Alcalfar", "Barranc de Rafalet", "Fort Marlborough", "Cala de Sant Esteve"],
        [[39.8140, 4.2810], [39.8280, 4.2880], [39.8450, 4.2950], [39.8630, 4.2990]],
    ),
    (
        "gr223-etapa-20-cala-sant-esteve-mao",
        "GR-223 Etapa 20: Cala de Sant Esteve a Maó",
        "Maó",
        "Llevant de Menorca",
        6.0,
        75,
        "Fàcil",
        "1h 45min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Cala de Sant Esteve", "Es Castell", "Port de Maó"],
        "Recorregut urbà pel gran port natural de Maó. Respectar les normes de circulació per voreres i passeigs. Tancament oficial de la volta sencera a l'illa.",
        "Darrera etapa del GR-223 que recorre Es Castell (Cales Fonts) i voreja el port de Maó fins a completar el perímetre complet de 185 km de l'illa.",
        39.8630,
        4.2990,
        "Cala de Sant Esteve",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=GR-223+Etapa+20+Cala+Sant+Esteve+Mao",
        ["Cala de Sant Esteve", "Es Castell (Cales Fonts)", "Castell de Sant Felip", "Port de Maó"],
        [[39.8630, 4.2990], [39.8720, 4.2980], [39.8800, 4.2910], [39.8942, 4.2647]],
    ),
    (
        "gr223-variant-far-de-cavalleria",
        "Variant GR-223: Far de Cavalleria",
        "Es Mercadal",
        "Nord de Menorca",
        6.5,
        85,
        "Fàcil",
        "1h 45min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Cala Tirant", "Sanitja"],
        "Tram molt obert i exposat al vent fort de tramuntana. Extremar la precaució escolta als penya-segats de més de 90 metres d'alçada del Cap de Cavalleria.",
        "Variant del Camí de Cavalls que arriba fins al punt més septentrional de Menorca, el Far de Cavalleria, passant per les ruïnes romanes del port de Sanisera.",
        40.0450,
        4.1130,
        "Cala Tirant / Port de Sanitja",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=Variant+Far+de+Cavalleria+Menorca",
        ["Port de Sanitja (Sanisera romana)", "Cap de Cavalleria", "Far de Cavalleria", "Penya-segats del Cap"],
        [[40.0450, 4.1130], [40.0580, 4.1010], [40.0750, 4.0980], [40.0880, 4.0930]],
    ),
    (
        "gr223-variant-barranc-dalgendar",
        "Variant GR-223: Barranc d'Algendar",
        "Ferreries",
        "Sud de Menorca",
        7.5,
        40,
        "Moderada",
        "2h 15min",
        ["Llops/Daines", "Pioners/Rangers", "Rutes"],
        ["Ferreries", "Brolladors d'Algendar", "Cala Galdana"],
        "Barranc profund d'alt valor biològic; humitat elevada i camí fangós a prop dels brolladors. Respectar els horts tradicionals i tancar sempre les barreres.",
        "Variant que recorre el canyó més important de Menorca, amb parets verticals de 80 metres, exuberant vegetació de ribera i brolladors d'aigua permanents.",
        39.9830,
        3.9820,
        "Ferreries (accés camí d'Algendar)",
        "https://www.wikiloc.com/rutas/senderismo/espana/illes-balears?q=Variant+Barranc+Algendar+Ferreries",
        ["Pas d'en Revull", "Cova del Càrritx", "Brollador d'aigua dolça", "Desembocadura de Cala Galdana"],
        [[39.9830, 3.9820], [39.9650, 3.9740], [39.9510, 3.9680], [39.9370, 3.9630]],
    ),
]


def build_routes():
    routes = []
    for item in STAGES_DATA:
        (
            slug,
            nom,
            municipi,
            zona,
            dist,
            desn,
            dif,
            durada,
            apte,
            aigua,
            seguretat,
            desc,
            lat,
            lon,
            origen,
            wiki,
            interes,
            track,
        ) = item

        route = {
            "slug": slug,
            "nom": nom,
            "municipi": municipi,
            "zona": zona,
            "illa": "Menorca",
            "distancia_km": dist,
            "desnivell_positiu_m": desn,
            "dificultat": dif,
            "durada_estimada": durada,
            "apte_unitats": apte,
            "punts_aigua": aigua,
            "consells_seguretat": seguretat,
            "descripcio": desc,
            "lat": lat,
            "lon": lon,
            "punt_origen": origen,
            "font": "Consell Insular de Menorca",
            "font_url": "https://www.gr223.info",
            "wikiloc_url": wiki,
            "track_coordinates": track,
            "punts_interes": interes,
        }
        routes.append(route)
    return routes


def main():
    routes = build_routes()
    print(f"Total Menorca routes to generate: {len(routes)}")
    assert len(routes) == 22, f"Expected 22 routes, got {len(routes)}"

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(routes, f, ensure_ascii=False, indent=2)

    print(f"Successfully generated {OUTPUT_FILE} ({len(routes)} routes).")


if __name__ == "__main__":
    main()
